### ISSUE TITLE
sunlight: rename to static-ct-api

### ISSUE THREAD

**Issue by FiloSottile** [C2SP/C2SP#82]
The use of the Sunlight name for both [the CT log implementation](https://sunlight.dev) and for the API specified in C2SP is causing confusion. There is consensus to rename the spec a boring "Static Certificate Transparency API" or `static-ct-api` for short.

https://groups.google.com/a/chromium.org/g/ct-policy/c/v9JzlbphYBs/m/LwMuqT4YAwAJ

We don't have a formal process for this, but I think applying the new spec name assignment process would be fine.

**Comment by str4d** [comment]
> We don't have a formal process for this, but I think applying the new spec name assignment process would be fine.

It is obviously fine to apply for a new spec name. It is less obviously fine to do so for a spec that will be identical to an existing spec, as there's confusion problems there. A spec rename falls in between these two cases, because the intention is that the old spec name either does not refer to a different spec (i.e. is aliased), or stops being used entirely. I think that makes it close to obviously fine to use the new spec name assignment process.

The next question is what happens with the old spec name. I think there are a couple of things here:
- If a spec has reached 1.0, then its spec name MUST be preserved indefinitely as an alias.
  - We add a 308 or 301 (permanent) redirect from the old name to the new name for all URLs that existed at the time of the rename.
  - We maybe consider doing so for all future URLs as well. This could be confusing (e.g. if a subsequent 2.0 version occurs unde the new name, should the old name that only had a 1.0 version be considered to have gained a 2.0?) but also might be necessary depending on how the C2SP spec hosting service operates.
- If a spec has not yet reached 1.0 (and is thus still in the draft phase with 0.Y versioning), then we can potentially just have a temporary alias.
  - We add a 307 or 302 (temporary) redirect from the old name to the new name for all URLs.
  - We monitor how much activity that redirect sees.
  - After some amount of time, we decide whether we need to change the redirect to a 308 or 301 (permanent), or can drop the redirect (freeing up the old name for subsequent reuse).
    - We might also take into account the amount of time that has elapsed between the old name being requested, and the rename being requested.
- The rename proposer should indicate what they want to happen to the old name as part of their rename request, subject to the above considerations.
  - The stewards have final say on what happens.

With the above in mind: ACK on the new name for this spec; with @FiloSottile's implicit approval as proposer, we have steward quorum (2/3).

**Comment by FiloSottile** [comment]
I am a big fan of URLs never changing, so I lean towards making aliases permanent except in exceptional circumstances.
