### ISSUE TITLE
endpoints are different between the tlog-tiles and the static-ct-api spec

### ISSUE THREAD

**Issue by josieang** [C2SP/C2SP#94]
I've noticed that in [tlog-tiles](https://github.com/C2SP/C2SP/blob/main/tlog-tiles.md#log-entries), the log entries are served at 
```
<prefix>/tile/entries/<N>[.p/<W>]
```
whereas in [static-ct-api](https://github.com/C2SP/C2SP/blob/main/static-ct-api.md#log-entries) the log entries are served at 
```
<monitoring prefix>/tile/data/<N>[.p/<W>]
```

Just wondering if we're planning to converge these definitions? And if so, which one?

**Comment by FiloSottile** [comment]
That's, unfortunately, not going to converge. The path difference is intended to signal a more fundamental difference: the format of "level -1" tiles is different in tlog-tiles and static-ct-api.

CT needs to store per-entry data that is however not part of the Merkle leaf (which is not great). We had three options

1. add support for additional data to tlog-tiles, encouraging future designs to make the same unfortunate design decision
2. store the CT additional data in a separate tile, significantly raising static-ct-api's storage and bandwidth requirements, because as-is the additional data compresses very well against the Merkle leaves
3. diverge the formats

and we begrudgingly picked 3.

/cc @C2SP/tlog-tiles

**Comment by FiloSottile** [comment]
By the way, FYI there is a static-ct-api entries tile parser (and a couple other useful functions) at https://pkg.go.dev/filippo.io/sunlight@main.

**Comment by josieang** [comment]
Interesting, that's really unfortunate I guess. Could we say this in the static-ct-api spec? Both sections in both specs are called 'LogEntries' and it's not immediately obvious that they're different.
